-- ⚠️⚠️ 실행 금지 (2026-07-15 무력화) ⚠️⚠️
-- 이 스크립트는 2026-07-12 main 감사 때 "안 쓰이는 죽은 스키마"로 판단해 작성됐지만,
-- sh↔main 병합(bd94491) 이후 아래 대상들은 전부 "살아있는" 객체가 됐다. 병합에서 sh 코드가
-- 채택되면서 다음이 실제로 이들을 사용한다:
--   • match_research_by_topic (RPC)        ← pipelineMemory.ts::getRecentResearch()가 호출(주제 유사도 검색).
--   • topic_filter_accumulated 등 토글 컬럼  ← 리서치 토글이 읽고, /api/brainstorm 이 insert 시 값을 씀.
-- 따라서 이 스크립트를 지금 실행하면 (1) 주제검색이 최신순으로 degrade, (2) 브레인스토밍 insert가
-- "컬럼 없음"으로 실패할 수 있다. 아래 명령들을 전부 주석 처리해 무력화한다. 되살릴 일 없으면 파일째 삭제 가능.
--
-- (원문 — 실행하지 말 것)
-- alter table brainstorm_runs drop column if exists topic_filter_accumulated;
-- alter table brainstorm_runs drop column if exists reimprove_topic_filter;
-- alter table tasks drop column if exists accumulated_topic_filter;
-- drop function if exists match_research_by_topic;
-- drop extension if exists pg_trgm;
